package GUI;

import Database.Database;
import com.formdev.flatlaf.FlatDarculaLaf;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import kdesp73.databridge.connections.DatabaseConnection;
import kdesp73.databridge.helpers.QueryBuilder;
import kdesp73.themeLib.Theme;

/**
 *
 * @author tgeorg
 */
public class AboutFrame extends javax.swing.JFrame {

    SettingsFrame sf;
    ResourceBundle rb;
    Theme theme;

    Color pc = new Color(162, 119, 255);
    Color bg = new Color(21, 20, 27);
    Color sep = new Color(187, 187, 187);

    private static final String FILEPATH = System.getProperty("user.dir").replaceAll(Pattern.quote("\\"), "/");

    /**
     * Creates new form AboutFrame
     */
    public AboutFrame() {
        // Frame setup
        initComponents();
        this.theme = GUIFunctions.setupFrame(this, "About");
    }

    public AboutFrame(SettingsFrame sf) {
        FlatDarculaLaf.setup();
        // Frame setup 
        initComponents();
        this.theme = GUIFunctions.setupFrame(this, "About");

        configureFrameProperties();

        githubLabel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (githubLabel.getMouseListeners().length != 0) {
                    githubLabel.removeMouseListener(githubLabel.getMouseListeners()[0]);
                }

                if (e.getButton() != MouseEvent.BUTTON1 && e.getClickCount() > 1) {
                    return;
                }
                try {
                    Desktop.getDesktop().browse(new URI("https://github.com/ThanasisGeorg"));
                } catch (URISyntaxException | IOException ex) {
                    //It looks like there's a problem
                }
            }
        });

        this.sf = sf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutPanel = new javax.swing.JPanel();
        synopsisLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        synopsisScrollPane = new javax.swing.JScrollPane();
        synopsisTextArea = new javax.swing.JTextArea();
        licenceLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        licenceScrollPane = new javax.swing.JScrollPane();
        licenceTextArea = new javax.swing.JTextArea();
        madeByLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        ownerLabel = new javax.swing.JLabel();
        contactInfo1Label = new javax.swing.JLabel();
        githubLabel = new javax.swing.JLabel();
        contactInfo2Label = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        aboutPanel.setName("bg"); // NOI18N

        synopsisLabel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        synopsisLabel.setText("<html><p style=\"text-align:center\"><b>Synopsis</p> </html>");
        synopsisLabel.setName("textbox"); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(187, 187, 187));
        jSeparator1.setForeground(new java.awt.Color(187, 187, 187));
        jSeparator1.setName("extra_2"); // NOI18N
        jSeparator1.setOpaque(true);

        synopsisTextArea.setEditable(false);
        synopsisTextArea.setColumns(20);
        synopsisTextArea.setLineWrap(true);
        synopsisTextArea.setRows(3);
        synopsisTextArea.setText("A program to manage your bank accounts using functionalities sush as \n  -login/sign in\n  -deposit\n  -delete\nThere are also functionalities that are gonna be  useful to imporve your experience such as\n  -change language (English/Greek)\n  -change theme (Dark/Light)\n  -change password\n\nIt is available in two versions:\n  -GUI version (with Java Swing)\n  -terminal version");
        synopsisTextArea.setCaretPosition(0);
        synopsisScrollPane.setViewportView(synopsisTextArea);

        licenceLabel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        licenceLabel.setText("<html><p style=\"text-align:center\"><b>Licence</p> </html>");
        licenceLabel.setName("textbox"); // NOI18N

        jSeparator2.setBackground(new java.awt.Color(187, 187, 187));
        jSeparator2.setForeground(new java.awt.Color(187, 187, 187));
        jSeparator2.setName("extra_2"); // NOI18N
        jSeparator2.setOpaque(true);

        licenceTextArea.setEditable(false);
        licenceTextArea.setColumns(20);
        licenceTextArea.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        licenceTextArea.setRows(5);
        licenceTextArea.setText("MIT License\n\nCopyright (c) 2023 Athanasios Georgalis\n\nPermission is hereby granted, free of charge, to any person\nobtaining a copy of this software and associated documentation\nfiles (the \"Software\"), to deal in the Software without restriction,\nincluding without limitation the rights to use, copy, modify, merge,\npublish, distribute, sublicense, and/or sell copies of the Software,\nand to permit persons to whom the Software is furnished to do so, \nsubject to the following conditions:\n\nThe above copyright notice and this permission notice shall be \nincluded in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY\nOF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT\nLIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS \nFOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT \nSHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR\nANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN \nACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE \nOR OTHER DEALINGS IN THE SOFTWARE.");
        licenceTextArea.setCaretPosition(0);
        licenceScrollPane.setViewportView(licenceTextArea);

        madeByLabel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        madeByLabel.setText("<html><p style=\"text-align:center\"><b>Made By & Contact Info</p> </html>");
        madeByLabel.setName("textbox"); // NOI18N

        jSeparator3.setBackground(new java.awt.Color(187, 187, 187));
        jSeparator3.setForeground(new java.awt.Color(187, 187, 187));
        jSeparator3.setName("extra_2"); // NOI18N
        jSeparator3.setOpaque(true);

        ownerLabel.setFont(new java.awt.Font("Manjari", 0, 20)); // NOI18N
        ownerLabel.setText("<html><p style=\"text-align:center\"><b>Athanasios Georgalis</p> </html>");
        ownerLabel.setName("textbox"); // NOI18N

        contactInfo1Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        contactInfo1Label.setText("<html><p style=\"text-align:center\"><b>GitHub:</p> </html>");
        contactInfo1Label.setName("textbox"); // NOI18N

        githubLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        githubLabel.setText("ThanasisGeorg");
        githubLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        githubLabel.setName("textbox"); // NOI18N

        contactInfo2Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        contactInfo2Label.setText("<html><p style=\"text-align:center\"><b>Email:</p> </html>");
        contactInfo2Label.setName("textbox"); // NOI18N

        emailLabel.setText("thanasisgeorg03@gmail.com");
        emailLabel.setName("textbox"); // NOI18N

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addComponent(contactInfo2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailLabel))
                    .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(synopsisLabel)
                        .addComponent(jSeparator1))
                    .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(licenceLabel, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(synopsisScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenceScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(madeByLabel)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addComponent(contactInfo1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(githubLabel))
                    .addComponent(ownerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(synopsisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(synopsisScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(licenceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(licenceScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(madeByLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(ownerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(githubLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactInfo1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactInfo2Label))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configureFrameProperties() {
        DatabaseConnection db = Database.connection();

        String languageName = "";
        ResultSet rs = db.executeQuery(new QueryBuilder().select("Language").from("Settings").build());
        try {
            rs.next();
            languageName = rs.getString(1);
        } catch (SQLException ex) {
            Logger.getLogger(SettingsFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            db.close();
        }

        if (languageName.equals("English")) {
            GUIFunctions.setTexts(this, Locale.US);
        } else if (languageName.equals("Greek")) {
            GUIFunctions.setTexts(this, Locale.of("el", "GR"));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutFrame().setVisible(true);
            }
        });
    }

    public JLabel getContactInfo1Label() {
        return contactInfo1Label;
    }

    public JLabel getContactInfo2Label() {
        return contactInfo2Label;
    }

    public JLabel getEmailLabel() {
        return emailLabel;
    }

    public JLabel getGithubLabel() {
        return githubLabel;
    }

    public JLabel getLicenceLabel() {
        return licenceLabel;
    }

    public JLabel getMadeByLabel() {
        return madeByLabel;
    }

    public JLabel getOwnerLabel() {
        return ownerLabel;
    }

    public JLabel getSynopsisLabel() {
        return synopsisLabel;
    }

    public JTextArea getSynopsisTextArea() {
        return synopsisTextArea;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel contactInfo1Label;
    private javax.swing.JLabel contactInfo2Label;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel githubLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel licenceLabel;
    private javax.swing.JScrollPane licenceScrollPane;
    private javax.swing.JTextArea licenceTextArea;
    private javax.swing.JLabel madeByLabel;
    private javax.swing.JLabel ownerLabel;
    private javax.swing.JLabel synopsisLabel;
    private javax.swing.JScrollPane synopsisScrollPane;
    private javax.swing.JTextArea synopsisTextArea;
    // End of variables declaration//GEN-END:variables
}
