package GUI;

import com.formdev.flatlaf.FlatDarculaLaf;
import java.awt.Color;
import java.util.ResourceBundle;
import java.util.regex.Pattern;
import javax.swing.text.DefaultCaret;
import kdesp73.themeLib.Theme;

/**
 *
 * @author tgeorg
 */
public class AboutFrame extends javax.swing.JFrame {

    SettingsFrame sf;
    ResourceBundle rb;
    Theme theme;

    Color pc = new Color(162, 119, 255);
    Color bg = new Color(21, 20, 27);
    Color sep = new Color(187, 187, 187);

    private static final String FILEPATH = System.getProperty("user.dir").replaceAll(Pattern.quote("\\"), "/");
    
    /**
     * Creates new form AboutFrame
     */
    public AboutFrame() {
        // Frame setup
        initComponents();
        this.theme = GUIFunctions.setupFrame(this, "About");
    }
    
    public AboutFrame(SettingsFrame sf) {
        FlatDarculaLaf.setup();
        // Frame setup 
        initComponents();
        this.theme = GUIFunctions.setupFrame(this, "About");        
        
        this.sf = sf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutPanel = new javax.swing.JPanel();
        synopsisLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        synopsisScrollPane = new javax.swing.JScrollPane();
        synopsisTextArea = new javax.swing.JTextArea();
        licenceLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        licenceScrollPane = new javax.swing.JScrollPane();
        licenceTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        aboutPanel.setName("bg"); // NOI18N

        synopsisLabel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        synopsisLabel.setText("<html><p style=\"text-align:center\"><b>Synopsis</p> </html>");
        synopsisLabel.setName("textbox"); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(187, 187, 187));
        jSeparator1.setForeground(new java.awt.Color(187, 187, 187));
        jSeparator1.setName("fg_2"); // NOI18N

        synopsisTextArea.setEditable(false);
        synopsisTextArea.setColumns(20);
        synopsisTextArea.setLineWrap(true);
        synopsisTextArea.setRows(3);
        synopsisTextArea.setText("A program to manage your bank accountswritten in Java, with the use of SQLite.\nIt is available in two versions:\n-terminal version\n-GUI version (with Java Swing)");
        synopsisScrollPane.setViewportView(synopsisTextArea);

        licenceLabel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        licenceLabel.setText("<html><p style=\"text-align:center\"><b>Licence</p> </html>");
        licenceLabel.setName("textbox"); // NOI18N

        jSeparator2.setBackground(new java.awt.Color(187, 187, 187));
        jSeparator2.setForeground(new java.awt.Color(187, 187, 187));
        jSeparator2.setName("fg_2"); // NOI18N

        licenceTextArea.setEditable(false);
        licenceTextArea.setColumns(20);
        licenceTextArea.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        licenceTextArea.setRows(5);
        licenceTextArea.setText("MIT License\n\nCopyright (c) 2023 Athanasios Georgalis\n\nPermission is hereby granted, free of charge, to any person\nobtaining a copy of this software and associated documentation\nfiles (the \"Software\"), to deal in the Software without restriction,\nincluding without limitation the rights to use, copy, modify, merge,\npublish, distribute, sublicense, and/or sell copies of the Software,\nand to permit persons to whom the Software is furnished to do so, \nsubject to the following conditions:\n\nThe above copyright notice and this permission notice shall be \nincluded in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY\nOF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT\nLIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS \nFOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT \nSHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR\nANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN \nACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE \nOR OTHER DEALINGS IN THE SOFTWARE.");
        licenceTextArea.setCaretPosition(0);
        licenceScrollPane.setViewportView(licenceTextArea);

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(synopsisLabel)
                        .addComponent(jSeparator1))
                    .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(licenceLabel, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(licenceScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(synopsisScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(synopsisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(synopsisScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(licenceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(licenceScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel licenceLabel;
    private javax.swing.JScrollPane licenceScrollPane;
    private javax.swing.JTextArea licenceTextArea;
    private javax.swing.JLabel synopsisLabel;
    private javax.swing.JScrollPane synopsisScrollPane;
    private javax.swing.JTextArea synopsisTextArea;
    // End of variables declaration//GEN-END:variables
}
